INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Susan','Sargent','egestas.a@sit.com','2021-09-14','');
INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Grady','Garza','rhoncus@ametfaucibus.org','2021-03-01','');
INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Aubrey','Mccall','aliquam@vel.edu','2020-03-20','');
INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Joshua','Baird','malesuada.ut.sem@tincidunttempus.org','2020-06-17','');
INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Charles','Dickerson','felis.adipiscing.fringilla@atarcu.net','2020-03-09','');
INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Brooke','Olson','tempor@enimnec.org','2021-03-17','');
INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Miriam','Griffith','auctor.vitae@interdumenimnon.org','2021-07-18','');
INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Willow','Macdonald','Duis.ac.arcu@ipsumSuspendisse.org','2021-02-23','');
INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Valentine','Banks','elit@diamPellentesquehabitant.co.uk','2021-08-05','');
INSERT INTO `clients` (`name`,`surname`,`email`,`create_at`,`photo`) VALUES ('Galvin','Sampson','egestas@molestiedapibusligula.net','2021-04-04','');
INSERT INTO clients (name,surname,email,create_at,photo) VALUES ('Julian','Townsend','Proin@velitegetlaoreet.co.uk','2020-12-21',''),('Zeph','Mcdaniel','eleifend.Cras.sed@DonectinciduntDonec.edu','2020-05-19',''),('Martena','Romero','Duis.elementum@dis.co.uk','2021-11-06',''),('Gisela','Calhoun','dolor.quam.elementum@Craseutellus.org','2020-10-22',''),('Tanisha','Delacruz','semper.egestas.urna@et.net','2020-05-29',''),('Leo','Aguilar','Praesent.eu.nulla@aliquam.ca','2021-06-17',''),('Simon','Raymond','Morbi@ipsumPhasellus.com','2022-01-20',''),('Maxwell','Holcomb','a.magna@molestietellusAenean.com','2020-08-02',''),('Michelle','Schultz','urna@mattisornarelectus.edu','2021-09-28',''),('Ignacia','Newton','turpis.vitae.purus@velesttempor.org','2020-07-11',''),('Iris','Fleming','nonummy.ac.feugiat@a.net','2020-04-27',''),('Kendall','Pugh','ut.cursus@tellusimperdiet.co.uk','2020-06-28',''),('Sawyer','Elliott','natoque.penatibus.et@Maecenasmalesuadafringilla.net','2021-06-30',''),('Nolan','West','Duis.dignissim.tempor@placerataugue.org','2021-12-17',''),('Tallulah','Shelton','In@sociosqu.ca','2021-11-13',''),('Sybill','Mccray','parturient@nuncsed.edu','2020-09-17',''),('Hollee','Farmer','sagittis.placerat@non.edu','2020-07-10',''),('Grace','Wise','cursus.vestibulum@imperdietullamcorperDuis.ca','2020-07-29',''),('Amber','Maynard','sem.magna@Mauris.net','2021-10-16',''),('Abraham','Rollins','Proin.non.massa@acfermentum.net','2021-08-26',''),('Noah','Long','molestie.in@magnaSuspendisse.net','2020-08-15',''),('Grady','Murray','eu.sem@sit.net','2020-09-06',''),('Demetrius','Brennan','Pellentesque.habitant.morbi@miacmattis.co.uk','2021-08-08',''),('Cynthia','Griffith','adipiscing@molestiearcu.ca','2020-04-05',''),('Germaine','Mills','a.enim@Donecest.co.uk','2020-10-25','');
INSERT INTO clients (name,surname,email,create_at,photo) VALUES ('Bruce','Rush','purus.accumsan.interdum@sit.edu','2022-01-16',''),('Kareem','Phelps','eros.non@atauctor.com','2020-05-12',''),('Daryl','Holden','mauris.Suspendisse@temporarcu.co.uk','2020-07-04',''),('Keelie','Blevins','nec@Proineget.ca','2021-08-17',''),('Selma','Newton','lacus@veliteusem.net','2020-07-28',''),('Colby','Armstrong','iaculis.quis.pede@arcuVivamussit.com','2020-02-27',''),('Tallulah','Medina','Vivamus.nibh.dolor@etmalesuadafames.ca','2021-02-21',''),('Susan','Paul','Duis.dignissim.tempor@Suspendissenonleo.edu','2020-11-30',''),('Cyrus','Key','nulla@ornare.edu','2021-02-09',''),('Jane','Wade','nunc.risus@interdumNuncsollicitudin.co.uk','2021-06-26',''),('Fletcher','Christensen','vehicula.risus.Nulla@Nunc.edu','2021-10-20',''),('Arden','Reed','Nulla@a.co.uk','2021-01-18',''),('Acton','Wagner','convallis.erat@ultricesDuis.edu','2021-05-23',''),('Castor','Love','Integer.urna.Vivamus@mattisInteger.ca','2020-08-22',''),('Kareem','Hays','feugiat.non@nisiAenean.edu','2020-03-09',''),('Zachary','Williams','mauris@ut.ca','2021-04-13',''),('Berk','Woodward','non.quam.Pellentesque@ligulaAliquamerat.edu','2020-03-22',''),('Noah','Frederick','pede@egestasurna.co.uk','2021-04-20',''),('Yuri','Pittman','leo@loremsitamet.org','2020-08-27',''),('Eleanor','Vega','eros@Intincidunt.com','2022-01-05',''),('Fallon','Maynard','amet.lorem@molestiedapibus.co.uk','2020-02-19',''),('Melissa','Payne','tellus.Suspendisse.sed@anteipsumprimis.edu','2020-05-21',''),('Aubrey','Franco','Fusce.diam.nunc@malesuada.org','2021-02-04',''),('Rama','William','auctor.quis@nectempusscelerisque.net','2020-05-21',''),('McKenzie','Mccullough','pellentesque@adipiscing.ca','2020-09-28','');

INSERT INTO `products` (`name`,`price`,`create_at`) VALUES ('Panasonic LCD screen', 2600, NOW());
INSERT INTO `products` (`name`,`price`,`create_at`) VALUES ('Sony Digital Camera', 1500, NOW());
INSERT INTO `products` (`name`,`price`,`create_at`) VALUES ('Apple macbook pro', 2000, NOW());
INSERT INTO `products` (`name`,`price`,`create_at`) VALUES ('Sony notebook z110', 900, NOW());
INSERT INTO `products` (`name`,`price`,`create_at`) VALUES ('HP multifunctional f2280', 700, NOW());
INSERT INTO `products` (`name`,`price`,`create_at`) VALUES ('Bicycle gamma 26', 2500, NOW());
INSERT INTO `products` (`name`,`price`,`create_at`) VALUES ('Bamboo Bookstand ', 120, NOW());


INSERT INTO `invoices` (`description`,`observation`,`client_id`, `create_at`) VALUES ('office equipment invoice', null, 1, NOW());
INSERT INTO `invoice_items` (`amount`,`invoice_id`,`product_id`) VALUES (1, 1, 1);
INSERT INTO `invoice_items` (`amount`,`invoice_id`,`product_id`) VALUES (2, 1, 4);
INSERT INTO `invoice_items` (`amount`,`invoice_id`,`product_id`) VALUES (1, 1, 5);
INSERT INTO `invoice_items` (`amount`,`invoice_id`,`product_id`) VALUES (1, 1, 7);


INSERT INTO `invoices` (`description`,`observation`,`client_id`, `create_at`) VALUES ('bicycle invoice', 'some note', 1, NOW());
INSERT INTO `invoice_items` (`amount`,`invoice_id`,`product_id`) VALUES (3, 2, 6);